### PR TITLE
Fix #90.

### LINKED ISSUE #90: SIM_HOST plugin code may send messages ahead of time
In some cases, plugin simulation code on SIM_HOST may send messages ahead of time (before the APP_HOST is able to respond). Currently, there's one specific case: `cordova-plugin-device` tries to retrieve `cordova.version` ahead of time. With the merge of #21, it becomes consistently reproducible (in Device widget cordova version information is missing). Since the call never returns, the `.fail()` handler on such calls is not called either.

### PR DESCRIPTION
**Pull request by busykai**
Provide an API for the plugins to synchronize calls to the APP_HOST.

We had a few options to address issue #90. One of them was to simply delay premature messages to APP_HOST until it's ready on the server and the other embed plugin initialization into the lifecycle of the entire simulation.

This is an alternative approach which provides an API to the plugins to sync on for the messages which should be sent to the APP_HOST early in the initialization. I do think that unsolicited (by APP_HOST) messages and calls from SIM_HOST to APP_HOST should be a rare exception, but if they absolutely have to be sent, there's an API which allows them to do that in a coordinated manner. It does not impose any change on the plugins which do not need, just the ones that do need to use it.

Even the use case we have right now (`cordova-platform-device` plugin), should probably not be the case. Instead, `cordova.version` (and `cordova` in general) information should be returned to SIM_HOST with `app-plugin-list` message during the bootstrap.

Please let me know what you think.

@dlebu, @guillaumejenkins, @albertinad

### CODE REVIEW

**Comment by dlebu** [comment]
This looks good to me.

File: src/modules/sim-host/sim-status.js [hunk 1]
```diff
@@ -0,0 +1,31 @@
+// Copyright 2016 Intel Corporation. All rights reserved.
```
Comment (albertinad) [inline src/modules/sim-host/sim-status.js]: Should we add Microsoft license header too?

**Comment by albertinad** [comment]
Looks good to me!

File: src/modules/sim-host/sim-status.js (hunk 1 above)
Comment (busykai) [inline src/modules/sim-host/sim-status.js]: yes, sorry. @dlebu are you ok with both copyrights?

Comment (dlebu) [inline src/modules/sim-host/sim-status.js]: @busykai I will ask our legal team and get back to you.

Comment (busykai) [inline src/modules/sim-host/sim-status.js]: @dlebu, should we hold it for it? I'd rather changes this to the header the rest of the files have and then we'll figure out double copyright thing.

Comment (dlebu) [inline src/modules/sim-host/sim-status.js]: @busykai Sounds good. I emailed our legal team but we can modify it later if needed. Feel free to merge.

**Comment by busykai** [comment]
OK. Merging. Fixes #90.
