### PR TITLE
Simulator.prototype.startSimulation rethrow error so it can be handled

### LINKED ISSUE #266: Opens browser windows if target platform not in project
## Description

When you issue a command like `simulate browser` and the browser platform is not available, the CLI writes the error to the console, but still launches two browser windows

## Steps to Reproduce

Create a new Cordova project without adding any platforms
navigate to the project folder
execute `simulate browser`

## Actual Behavior
1. simulate command writes the following to the console:

```
~/dev/test » simulate browser                                 johnwargo@jmw-mac
SIM WARNING: Error starting the simulation
SIM ERROR: Project does not include the specified platform: browser
    at /Users/johnwargo/.nvm/versions/node/v8.9.4/lib/node_modules/cordova-simulate/node_modules/cordova-serve/src/platform.js:45:19
    at _fulfilled (/Users/johnwargo/.nvm/versions/node/v8.9.4/lib/node_modules/cordova-simulate/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/johnwargo/.nvm/versions/node/v8.9.4/lib/node_modules/cordova-simulate/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Users/johnwargo/.nvm/versions/node/v8.9.4/lib/node_modules/cordova-simulate/node_modules/q/q.js:816:13)
    at /Users/johnwargo/.nvm/versions/node/v8.9.4/lib/node_modules/cordova-simulate/node_modules/q/q.js:877:14
    at runSingle (/Users/johnwargo/.nvm/versions/node/v8.9.4/lib/node_modules/cordova-simulate/node_modules/q/q.js:137:13)
    at flush (/Users/johnwargo/.nvm/versions/node/v8.9.4/lib/node_modules/cordova-simulate/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:686:11)
```
2. Opens two empty browser windows

## Expected Behavior
1. Write an error to the console
2. Quit

## Software versions
Latest simulate, latest Cordova CLI.

### PR DESCRIPTION
**Pull request by iTOYS**
Fixes #266

### CODE REVIEW

File: src/server/simulator.js [hunk 1]
```diff
@@ -167,11 +167,11 @@ Simulator.prototype.startSimulation = function () {
 
             this._state = Simulator.State.RUNNING;
         }.bind(this))
-        .fail(function (error) {
+        .catch(function (error) {
             log.warning('Error starting the simulation');
-            log.error(error);
```
Comment (ruslan-bikkinin) [inline src/server/simulator.js]: Could you please clarify why should we delete this line? Could it lead to loss of logging of error?

Comment (iTOYS) [reply src/server/simulator.js]: We'd like to avoid double logs output. Error should be handled by caller
